country_list=[{'label': 'Global Result', 'value':'Global Result'},{'label': 'US', 'value': 'US'}, {'label': 'India', 'value': 'India'}, {'label': 'Brazil', 'value': 'Brazil'}, {'label': 'Russia', 'value': 'Russia'}, {'label': 'Colombia', 'value': 
'Colombia'}, {'label': 'Peru', 'value': 'Peru'}, {'label': 'Spain', 'value': 'Spain'}, {'label': 'Mexico', 'value': 'Mexico'}, {'label': 'Argentina', 'value': 'Argentina'}, {'label': 'South Africa', 'value': 'South Africa'}, {'label': 'France', 'value': 'France'}, {'label': 'Chile', 'value': 'Chile'}, {'label': 'Iran', 'value': 'Iran'}, {'label': 'United Kingdom', 'value': 'United Kingdom'}, {'label': 'Bangladesh', 'value': 'Bangladesh'}, {'label': 'Iraq', 'value': 'Iraq'}, {'label': 'Saudi Arabia', 'value': 'Saudi Arabia'}, {'label': 'Turkey', 'value': 'Turkey'}, {'label': 'Italy', 'value': 'Italy'}, {'label': 'Pakistan', 'value': 'Pakistan'}, {'label': 'Philippines', 'value': 'Philippines'}, {'label': 'Germany', 'value': 'Germany'}, {'label': 'Indonesia', 'value': 'Indonesia'}, {'label': 'Israel', 'value': 'Israel'}, {'label': 'Ukraine', 'value': 'Ukraine'}, {'label': 'Canada', 'value': 'Canada'}, {'label': 'Ecuador', 'value': 'Ecuador'}, {'label': 'Bolivia', 'value': 'Bolivia'}, {'label': 'Romania', 'value': 'Romania'}, {'label': 'Netherlands', 'value': 'Netherlands'}, {'label': 'Qatar', 'value': 'Qatar'}, {'label': 'Morocco', 'value': 'Morocco'}, {'label': 'Belgium', 'value': 'Belgium'}, {'label': 'Dominican Republic', 'value': 'Dominican Republic'}, {'label': 'Panama', 'value': 'Panama'}, {'label': 'Kazakhstan', 'value': 'Kazakhstan'}, {'label': 'Kuwait', 'value': 'Kuwait'}, {'label': 'Egypt', 'value': 'Egypt'}, {'label': 'Oman', 'value': 'Oman'}, {'label': 'United Arab Emirates', 'value': 'United Arab Emirates'}, {'label': 'Sweden', 'value': 'Sweden'}, {'label': 'Poland', 'value': 'Poland'}, {'label': 'Guatemala', 'value': 'Guatemala'}, {'label': 'China', 'value': 'China'}, {'label': 'Japan', 'value': 'Japan'}, {'label': 'Belarus', 'value': 'Belarus'}, {'label': 'Nepal', 'value': 'Nepal'}, {'label': 'Honduras', 'value': 'Honduras'}, {'label': 'Portugal', 'value': 'Portugal'}, {'label': 'Costa Rica', 'value': 'Costa Rica'}, {'label': 'Ethiopia', 'value': 'Ethiopia'}, {'label': 'Venezuela', 'value': 'Venezuela'}, {'label': 'Bahrain', 'value': 'Bahrain'}, {'label': 'Czechia', 'value': 'Czechia'}, {'label': 'Nigeria', 'value': 'Nigeria'}, {'label': 'Singapore', 'value': 'Singapore'}, {'label': 'Uzbekistan', 'value': 'Uzbekistan'}, {'label': 'Switzerland', 'value': 'Switzerland'}, {'label': 'Moldova', 'value': 'Moldova'}, {'label': 'Algeria', 'value': 'Algeria'}, {'label': 'Armenia', 'value': 'Armenia'}, {'label': 'Kyrgyzstan', 'value': 'Kyrgyzstan'}, {'label': 'Ghana', 'value': 'Ghana'}, {'label': 'Austria', 'value': 'Austria'}, {'label': 'Azerbaijan', 'value': 'Azerbaijan'}, {'label': 'Paraguay', 'value': 'Paraguay'}, {'label': 'West Bank and Gaza', 'value': 'West Bank and Gaza'}, {'label': 'Afghanistan', 'value': 'Afghanistan'}, {'label': 'Kenya', 'value': 'Kenya'}, {'label': 'Lebanon', 'value': 'Lebanon'}, {'label': 'Ireland', 'value': 'Ireland'}, {'label': 'Libya', 'value': 'Libya'}, {'label': 'Serbia', 'value': 'Serbia'}, {'label': 'El Salvador', 'value': 'El Salvador'}, {'label': 'Denmark', 'value': 'Denmark'}, {'label': 'Bosnia and Herzegovina', 'value': 'Bosnia and Herzegovina'}, {'label': 'Australia', 'value': 'Australia'}, {'label': 'Hungary', 'value': 'Hungary'}, {'label': 'Korea, South', 'value': 'Korea, South'}, {'label': 'Cameroon', 'value': 'Cameroon'}, {'label': 'Bulgaria', 'value': 'Bulgaria'}, {'label': "Cote d'Ivoire", 'value': "Cote d'Ivoire"}, {'label': 'Greece', 'value': 
'Greece'}, {'label': 'North Macedonia', 'value': 'North Macedonia'}, {'label': 'Tunisia', 'value': 'Tunisia'}, {'label': 'Croatia', 'value': 'Croatia'}, {'label': 'Madagascar', 'value': 'Madagascar'}, {'label': 'Senegal', 'value': 'Senegal'}, {'label': 'Zambia', 'value': 'Zambia'}, {'label': 'Norway', 'value': 'Norway'}, {'label': 'Sudan', 'value': 'Sudan'}, {'label': 'Albania', 'value': 'Albania'}, {'label': 'Kosovo', 'value': 'Kosovo'}, {'label': 'Burma', 'value': 'Burma'}, {'label': 'Malaysia', 'value': 'Malaysia'}, {'label': 'Namibia', 
'value': 'Namibia'}, {'label': 'Congo (Kinshasa)', 'value': 'Congo (Kinshasa)'}, {'label': 'Guinea', 'value': 'Guinea'}, {'label': 'Montenegro', 'value': 'Montenegro'}, {'label': 'Maldives', 'value': 'Maldives'}, {'label': 'Slovakia', 'value': 'Slovakia'}, {'label': 'Jordan', 'value': 'Jordan'}, {'label': 'Finland', 'value': 'Finland'}, {'label': 'Tajikistan', 'value': 'Tajikistan'}, {'label': 'Gabon', 'value': 'Gabon'}, {'label': 'Haiti', 'value': 'Haiti'}, {'label': 'Mozambique', 'value': 'Mozambique'}, {'label': 'Luxembourg', 'value': 'Luxembourg'}, {'label': 'Uganda', 'value': 'Uganda'}, {'label': 'Zimbabwe', 'value': 'Zimbabwe'}, {'label': 'Mauritania', 'value': 'Mauritania'}, {'label': 'Jamaica', 'value': 'Jamaica'}, {'label': 'Georgia', 'value': 'Georgia'}, {'label': 'Cabo Verde', 'value': 'Cabo Verde'}, {'label': 'Malawi', 'value': 'Malawi'}, {'label': 'Slovenia', 'value': 'Slovenia'}, {'label': 'Cuba', 'value': 'Cuba'}, {'label': 'Eswatini', 'value': 'Eswatini'}, {'label': 'Djibouti', 'value': 'Djibouti'}, {'label': 'Nicaragua', 'value': 'Nicaragua'}, {'label': 'Equatorial Guinea', 'value': 'Equatorial Guinea'}, {'label': 'Congo (Brazzaville)', 'value': 'Congo (Brazzaville)'}, {'label': 'Angola', 'value': 'Angola'}, {'label': 'Suriname', 'value': 'Suriname'}, {'label': 'Rwanda', 'value': 'Rwanda'}, {'label': 'Central African Republic', 'value': 'Central African Republic'}, {'label': 'Lithuania', 'value': 'Lithuania'}, {'label': 'Trinidad and Tobago', 'value': 'Trinidad and Tobago'}, {'label': 'Syria', 'value': 'Syria'}, {'label': 'Bahamas', 'value': 'Bahamas'}, {'label': 'Somalia', 'value': 'Somalia'}, {'label': 'Gambia', 'value': 'Gambia'}, {'label': 'Thailand', 'value': 'Thailand'}, {'label': 'Sri Lanka', 'value': 'Sri Lanka'}, {'label': 'Estonia', 'value': 'Estonia'}, {'label': 'Botswana', 'value': 'Botswana'}, {'label': 'Mali', 'value': 'Mali'}, {'label': 'Malta', 'value': 'Malta'}, {'label': 'Guyana', 'value': 'Guyana'}, {'label': 'Iceland', 'value': 'Iceland'}, {'label': 'South Sudan', 'value': 'South Sudan'}, {'label': 'Benin', 'value': 'Benin'}, {'label': 'Guinea-Bissau', 'value': 'Guinea-Bissau'}, {'label': 'Sierra Leone', 'value': 'Sierra Leone'}, {'label': 'Uruguay', 'value': 'Uruguay'}, {'label': 'Burkina Faso', 'value': 'Burkina Faso'}, {'label': 'Yemen', 'value': 'Yemen'}, {'label': 'Andorra', 'value': 'Andorra'}, {'label': 'Belize', 'value': 'Belize'}, {'label': 'New Zealand', 'value': 'New Zealand'}, {'label': 'Latvia', 'value': 'Latvia'}, {'label': 'Togo', 'value': 'Togo'}, {'label': 'Cyprus', 'value': 'Cyprus'}, {'label': 'Lesotho', 'value': 'Lesotho'}, {'label': 'Liberia', 'value': 'Liberia'}, {'label': 'Niger', 'value': 'Niger'}, {'label': 'Chad', 'value': 'Chad'}, {'label': 'Vietnam', 'value': 'Vietnam'}, {'label': 'Sao Tome and Principe', 'value': 'Sao Tome and Principe'}, {'label': 'San Marino', 'value': 'San Marino'}, {'label': 'Papua New Guinea', 'value': 'Papua New Guinea'}, {'label': 'Taiwan*', 'value': 'Taiwan*'}, {'label': 'Tanzania', 'value': 'Tanzania'}, {'label': 'Burundi', 'value': 'Burundi'}, {'label': 'Comoros', 'value': 'Comoros'}, {'label': 'Eritrea', 'value': 'Eritrea'}, {'label': 'Mauritius', 'value': 'Mauritius'}, {'label': 'Mongolia', 'value': 'Mongolia'}, {'label': 'Bhutan', 'value': 'Bhutan'}, {'label': 'Cambodia', 'value': 'Cambodia'}, {'label': 'Monaco', 'value': 'Monaco'}, {'label': 'Barbados', 'value': 'Barbados'}, {'label': 'Brunei', 'value': 'Brunei'}, {'label': 'Seychelles', 'value': 'Seychelles'}, {'label': 'Liechtenstein', 'value': 'Liechtenstein'}, {'label': 'Antigua and Barbuda', 'value': 'Antigua and Barbuda'}, {'label': 'Saint Vincent and the Grenadines', 'value': 'Saint Vincent and the Grenadines'}, {'label': 'Fiji', 'value': 'Fiji'}, {'label': 'Dominica', 'value': 'Dominica'}, {'label': 'Timor-Leste', 'value': 'Timor-Leste'}, {'label': 'Saint Lucia', 'value': 'Saint Lucia'}, {'label': 'Grenada', 'value': 'Grenada'}, {'label': 'Laos', 'value': 'Laos'}, {'label': 'Saint Kitts and Nevis', 'value': 'Saint Kitts and Nevis'}, {'label': 'Holy See', 'value': 'Holy See'}, {'label': 'Western Sahara', 'value': 'Western Sahara'}]










codes={'AD': 'Andorra',
 'AE': 'United Arab Emirates',
 'AF': 'Afghanistan',
 'AG': 'Antigua and Barbuda',
 'AL': 'Albania',
 'AM': 'Armenia',
 'AO': 'Angola',
 'AR': 'Argentina',
 'AT': 'Austria',
 'AU': 'Australia',
 'AZ': 'Azerbaijan',
 'BA': 'Bosnia and Herzegovina',
 'BB': 'Barbados',
 'BD': 'Bangladesh',
 'BE': 'Belgium',
 'BF': 'Burkina Faso',
 'BG': 'Bulgaria',
 'BH': 'Bahrain',
 'BI': 'Burundi',
 'BJ': 'Benin',
 'BN': 'Brunei',
 'BO': 'Bolivia',
 'BR': 'Brazil',
 'BS': 'Bahamas',
 'BT': 'Bhutan',
 'BW': 'Botswana',
 'BY': 'Belarus',
 'BZ': 'Belize',
 'CA': 'Canada',
 'CD': 'Congo (Kinshasa)',
 'CF': 'Central African Republic',
 'CG': 'Congo (Brazzaville)',
 'CH': 'Switzerland',
 'CI': "Cote d'Ivoire",
 'CL': 'Chile',
 'CM': 'Cameroon',
 'CN': 'China',
 'CO': 'Colombia',
 'CR': 'Costa Rica',
 'CU': 'Cuba',
 'CV': 'Cabo Verde',
 'CY': 'Cyprus',
 'CZ': 'Czechia',
 'DE': 'Germany',
 'DJ': 'Djibouti',
 'DK': 'Denmark',
 'DM': 'Dominica',
 'DO': 'Dominican Republic',
 'DZ': 'Algeria',
 'EC': 'Ecuador',
 'EE': 'Estonia',
 'EG': 'Egypt',
 'EH': 'Western Sahara',
 'ER': 'Eritrea',
 'ES': 'Spain',
 'ET': 'Ethiopia',
 'FI': 'Finland',
 'FJ': 'Fiji',
 'FR': 'France',
 'GA': 'Gabon',
 'GB': 'United Kingdom',
 'GD': 'Grenada',
 'GE': 'Georgia',
 'GH': 'Ghana',
 'GM': 'Gambia',
 'GN': 'Guinea',
 'GQ': 'Equatorial Guinea',
 'GR': 'Greece',
 'GT': 'Guatemala',
 'GW': 'Guinea-Bissau',
 'GY': 'Guyana',
 'HN': 'Honduras',
 'HR': 'Croatia',
 'HT': 'Haiti',
 'HU': 'Hungary',
 'ID': 'Indonesia',
 'IE': 'Ireland',
 'IL': 'Israel',
 'IN': 'India',
 'IQ': 'Iraq',
 'IR': 'Iran',
 'IS': 'Iceland',
 'IT': 'Italy',
 'JM': 'Jamaica',
 'JO': 'Jordan',
 'JP': 'Japan',
 'KE': 'Kenya',
 'KG': 'Kyrgyzstan',
 'KH': 'Cambodia',
 'KM': 'Comoros',
 'KN': 'Saint Kitts and Nevis',
 'KR': 'Korea, South',
 'KW': 'Kuwait',
 'KZ': 'Kazakhstan',
 'LA': 'Laos',
 'LB': 'Lebanon',
 'LC': 'Saint Lucia',
 'LI': 'Liechtenstein',
 'LK': 'Sri Lanka',
 'LR': 'Liberia',
 'LS': 'Lesotho',
 'LT': 'Lithuania',
 'LU': 'Luxembourg',
 'LV': 'Latvia',
 'LY': 'Libya',
 'MA': 'Morocco',
 'MC': 'Monaco',
 'MD': 'Moldova',
 'ME': 'Montenegro',
 'MG': 'Madagascar',
 'MK': 'North Macedonia',
 'ML': 'Mali',
 'MM': 'Burma',
 'MN': 'Mongolia',
 'MR': 'Mauritania',
 'MT': 'Malta',
 'MU': 'Mauritius',
 'MV': 'Maldives',
 'MW': 'Malawi',
 'MX': 'Mexico',
 'MY': 'Malaysia',
 'MZ': 'Mozambique',
 'NA': 'Namibia',
 'NG': 'Niger',
 'NI': 'Nicaragua',
 'NL': 'Netherlands',
 'NO': 'Norway',
 'NP': 'Nepal',
 'NZ': 'New Zealand',
 'OM': 'Oman',
 'PA': 'Panama',
 'PE': 'Peru',
 'PG': 'Papua New Guinea',
 'PH': 'Philippines',
 'PK': 'Pakistan',
 'PL': 'Poland',
 'PS': 'West Bank and Gaza',
 'PT': 'Portugal',
 'PY': 'Paraguay',
 'QA': 'Qatar',
 'RO': 'Romania',
 'RS': 'Kosovo',
 'RU': 'Russia',
 'RW': 'Rwanda',
 'SA': 'Saudi Arabia',
 'SC': 'Seychelles',
 'SD': 'Sudan',
 'SE': 'Sweden',
 'SG': 'Singapore',
 'SI': 'Slovenia',
 'SK': 'Slovakia',
 'SL': 'Sierra Leone',
 'SM': 'San Marino',
 'SN': 'Senegal',
 'SO': 'Somalia',
 'SR': 'Suriname',
 'SS': 'South Sudan',
 'ST': 'Sao Tome and Principe',
 'SV': 'El Salvador',
 'SY': 'Syria',
 'SZ': 'Eswatini',
 'TD': 'Chad',
 'TG': 'Togo',
 'TH': 'Thailand',
 'TJ': 'Tajikistan',
 'TL': 'Timor-Leste',
 'TN': 'Tunisia',
 'TR': 'Turkey',
 'TT': 'Trinidad and Tobago',
 'TW': 'Taiwan*',
 'TZ': 'Tanzania',
 'UA': 'Ukraine',
 'UG': 'Uganda',
 'US': 'US',
 'UY': 'Uruguay',
 'UZ': 'Uzbekistan',
 'VA': 'Holy See',
 'VC': 'Saint Vincent and the Grenadines',
 'VE': 'Venezuela',
 'VN': 'Vietnam',
 'YE': 'Yemen',
 'ZA': 'South Africa',
 'ZM': 'Zambia',
 'ZW': 'Zimbabwe',
  }